name: Python
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry=='1.1.4'
          poetry install
      - name: Lint and format
        run: |
          poetry run flake8 --select F streamlit_image_crop example.py
          poetry run black --check --diff streamlit_image_crop example.py
      - name: Check types
        run: |
          poetry run mypy streamlit_image_crop example.py
